os:
  - linux

services:
  - docker

language: generic

before_install:
  - packages/travis/travis.sh before_install

script:
  - packages/travis/travis.sh script

notifications:
  irc: "irc.rusnet.org.ru#ada-commits"

deploy:
  skip_cleanup: true
  on:
    condition: "$TRAVIS_OS_NAME = linux"
  provider: bintray
  file: packages/travis/bintray.json
  user: reznikmm
  key:
    secure: "UtJqqMV7YWljH84FdK5k5UbgolMhQ1FY7wkbmD1FvDgnReTOoWM3X7LudnjUp1W2ZE1TvkCVVjuV4ukRK15vxkkvVBhdLSzauXTjJ9wXgQEIZuCubCDK1WlI5Em8fHnA2WgLzldPS6n5wUT4Q56JRa7rLZ+9cija/hGueU4kGfN0DOb4Zpu9B3vSwJ4Lnew/X3pdHbdGh6tv69Fk0oNTzQHZ/XaL5D1aQitKk6ZrfLU2FdTSWV5JxVpuXMq03mGtpGGKcOB0j8wFO+gQDgK8OSwOEhI7DWqXkhqn1hwC/8BcmjP8JmO+VI4LprbE1VZ9DvgxRI//k5p6RaSs0PGtp4pGLuC4zaAh26zN3MFcGPRYBUGvBW1Q/bIWQw3T8s2ReM/TDfghUaNU5zoT6+HHpCmYDRJvXGif67t0JEX/KyXjUQf+lYht4MHH0EyZAOlAh1bdgLL4Nz+4ixMo2bkhZTIIUJGMbyX6YiFSpkQkGC3ms97bH39ger167tKQ1vlYx98cbMucrkrUgUCgBXAdHH4mG4sYp6YAAShs9EdEJn+wy0MP0HCbxZK1g6gj8NQFovaKWQuZUF1pKoMLoP7O6tKI0j9GsmpdnDINJYzhCKU8CchPbXn5tk1ccXbbQvCshlsUjt9/hJXf6wea3bSbaRbzMw2gx5wmRIevCkXZ8GQ="

