on: [push]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy RPM
    steps:
      - uses: actions/checkout@v2
        with:
          path: ada-pretty
      - uses: reznikmm/fedora-ada-action@v3
        with:
          spec: ada-pretty/packages/travis/ada-pretty.spec
      - name: Upload tar-ball to Bintray
        uses: reznikmm/upload-bintray-action@v3
        with:
          subject: reznikmm
          repository: matreshka
          package: ada-pretty
          version: head-fc33
          sourcePath: x86_64/*
          override: 1
          username: reznikmm
          apiKey: ${{secrets.BINTRAY_API_KEY}}
