on: [push]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy RPM
    steps:
      - uses: actions/checkout@v2
        with:
          path: ada-pretty
      - uses: reznikmm/fedora-ada-action@master
        with:
          spec: ada-pretty/packages/travis/ada-pretty.spec
